# Generated by Django 6.1.1 on 2026-09-21 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadlineMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Metric label, e.g. Projects Shipped', max_length=100)),
                ('target', models.IntegerField(help_text='Numerical counter target value, e.g. 12')),
                ('suffix', models.CharField(blank=True, default='', help_text="Suffix symbol, e.g. '+', '%'", max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order sequence')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this metric is displayed on the site')),
            ],
            options={
                'verbose_name': 'Headline Metric',
                'verbose_name_plural': 'Headline Metrics',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SprintPhaseMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(help_text='Phase label, e.g. Discovery, Design, Build', max_length=100)),
                ('duration_weeks', models.FloatField(default=1.0, help_text='Average duration in weeks (e.g. 1.5, 6.0)', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('order', models.PositiveIntegerField(default=0, help_text='Timeline sequence order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to include in the bar chart')),
            ],
            options={
                'verbose_name': 'Sprint Phase (Bar Chart)',
                'verbose_name_plural': 'Sprint Phases (Bar Chart)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TechSkillMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(help_text='Technology or domain name, e.g. Django, Next.js, AI/ML', max_length=100)),
                ('score', models.FloatField(default=8.0, help_text='Proficiency/Depth score out of 10.0 (e.g. 9.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order around the radar')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to include in the radar chart')),
            ],
            options={
                'verbose_name': 'Tech Skill Metric (Radar)',
                'verbose_name_plural': 'Tech Skill Metrics (Radar)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkMixMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Category name, e.g. Web App, AI/ML, PWA', max_length=100)),
                ('percentage', models.PositiveIntegerField(default=20, help_text='Share percentage or relative weight (e.g. 40)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('color_hex', models.CharField(blank=True, default='', help_text='Hex color code (e.g. #1481F8). Leave blank for default palette.', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order sequence')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to include in donut chart')),
            ],
            options={
                'verbose_name': 'Work Mix Category (Donut)',
                'verbose_name_plural': 'Work Mix Categories (Donut)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
