# Generated by Django 6.1.1 on 2026-09-05 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('tagline', models.CharField(max_length=280)),
                ('category', models.CharField(choices=[('web', 'Web App'), ('pwa', 'PWA'), ('ai_ml', 'AI/ML'), ('data', 'Data Engineering'), ('healthcare', 'Healthcare / Institutional System')], max_length=20)),
                ('status', models.CharField(choices=[('live', 'Live'), ('in_progress', 'In Progress'), ('archived', 'Archived')], default='live', max_length=20)),
                ('problem_statement', models.TextField()),
                ('approach', models.TextField()),
                ('key_features', models.JSONField(blank=True, default=list)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('demo_video_url', models.URLField(blank=True, null=True)),
                ('cover_image', models.ImageField(upload_to='projects/covers/')),
                ('team_credit', models.CharField(blank=True, max_length=300, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='projects.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('client_role', models.CharField(blank=True, max_length=150, null=True)),
                ('client_company', models.CharField(blank=True, max_length=150, null=True)),
                ('quote', models.TextField()),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_published', models.BooleanField(default=False)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='projects.project')),
            ],
        ),
    ]
