# Generated by Django 6.1.1 on 2026-09-05 17:09

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(upload_to='projects/covers/', validators=[apps.core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='projects/gallery/', validators=[apps.core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', validators=[apps.core.validators.validate_image_file]),
        ),
    ]
