# Generated by Django 6.1.1 on 2026-09-05 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon_name', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=280)),
                ('full_description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('proof_project', models.ForeignKey(blank=True, help_text="Kaunsa project isko prove karta hai — 'See it in action' link ke liye", null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
